import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

function directoryUrl(path) {
  const url = pathToFileURL(resolve(path));
  url.pathname = `${url.pathname.replace(/\/$/, '')}/`;
  return url;
}

const sourceRoot = process.env.CRANKWAVE_SOURCE_ROOT
  ? directoryUrl(process.env.CRANKWAVE_SOURCE_ROOT)
  : new URL('../../crankwave/data/engines/', import.meta.url);
const output = new URL('../generated/presets.ts', import.meta.url);
const definitions = [
  ['sequoia-3ur-fe-cleanroom', 'Toyota 3UR-FE 5.7L V8', 'sequoia-3ur-fe-cleanroom/engine.json'],
  ['bmw-m52b28', 'BMW M52B28 Inline-6', 'bmw-m52b28/engine.json'],
  ['bmw-m52tub28-cleanroom', 'BMW M52TU B28 Inline-6', 'bmw-m52tub28-cleanroom/engine.json'],
  ['cocentered-split-crank-v-twin-one-crank', 'Split-Crank V-Twin · One crank', 'cocentered-split-crank-v-twin/engine-a-one-crank.json'],
  ['cocentered-split-crank-v-twin-two-cranks', 'Split-Crank V-Twin · Two cranks', 'cocentered-split-crank-v-twin/engine-b-two-cranks.json'],
  ['cocentered-split-crank-v-twin-cross-crank-master', 'Split-Crank V-Twin · Cross-crank master rod', 'cocentered-split-crank-v-twin/engine-negative-cross-crank-master.json'],
  ['harley-evolution-1340-cleanroom', 'Harley Evolution 1340 V-Twin', 'harley-evolution-1340-cleanroom/engine.json'],
  ['honda-b18c5-cleanroom', 'Honda B18C5 Inline-4', 'honda-b18c5-cleanroom/engine.json'],
  ['kohler-ch750-cleanroom', 'Kohler CH750 V-Twin', 'kohler-ch750-cleanroom/engine.json'],
  ['radial-5-cleanroom', 'Radial 5', 'radial-5-cleanroom/engine.json'],
  ['raspy-muscle-620-cleanroom', '6.2L Rough Muscle V8', 'raspy-muscle-620-cleanroom/engine.json'],
  ['shovelhead-bank-local-heads', 'Shovelhead · Bank-local heads', 'shovelhead-bank-local-heads/engine.json'],
  ['shovelhead-bank-local-heads-separate-intakes', 'Shovelhead · Separate intakes', 'shovelhead-bank-local-heads/engine-separate-intakes.json'],
  ['shovelhead-bank-local-heads-swapped-heads', 'Shovelhead · Swapped heads', 'shovelhead-bank-local-heads/engine-swapped-heads.json'],
  ['subaru-ej25-cleanroom', 'Subaru EJ25 Flat-4', 'subaru-ej25-cleanroom/engine.json'],
];

const entries = [];
for (const [id, label, relativePath] of definitions) {
  const sourceJson = await readFile(new URL(relativePath, sourceRoot), 'utf8');
  const document = JSON.parse(sourceJson);
  entries.push({
    id,
    engineId: document.engine.identity.id,
    label,
    sourceJson,
    sourcePath: `crankwave/data/engines/${relativePath}`,
  });
}

const generated = `// Generated by tools/generate-presets.mjs from the authoritative Crankwave JSON.\n` +
  `// Do not hand-edit.\n` +
  `export const GENERATED_ENGINE_PRESETS = ${JSON.stringify(entries, null, 2)} as const;\n`;
await writeFile(output, generated);
