import { readFile, writeFile } from 'node:fs/promises';

const sourceRoot = new URL('../../engine-sim-wasm/data/engines/', import.meta.url);
const output = new URL('../generated/presets.ts', import.meta.url);
const definitions = [
  ['sequoia-3ur-fe-cleanroom', 'Toyota 3UR-FE 5.7L V8', 'sequoia-3ur-fe-cleanroom/engine.json'],
  ['bmw-m52tub28-cleanroom', 'BMW M52TU B28 Inline-6', 'bmw-m52tub28-cleanroom/engine.json'],
  ['honda-b18c5-cleanroom', 'Honda B18C5 Inline-4', 'honda-b18c5-cleanroom/engine.json'],
  ['subaru-ej25-cleanroom', 'Subaru EJ25 Flat-4', 'subaru-ej25-cleanroom/engine.json'],
];

const entries = [];
for (const [id, label, relativePath] of definitions) {
  const sourceJson = await readFile(new URL(relativePath, sourceRoot), 'utf8');
  entries.push({
    id,
    label,
    sourceJson,
    sourcePath: `engine-sim-wasm/data/engines/${relativePath}`,
  });
}

const generated = `// Generated by tools/generate-presets.mjs from the authoritative Engine Sim WASM JSON.\n` +
  `// Do not hand-edit.\n` +
  `export const GENERATED_ENGINE_PRESETS = ${JSON.stringify(entries, null, 2)} as const;\n`;
await writeFile(output, generated);
